import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-employer-stop-loss-claims-recovery",
  "engine": "recovery",
  "title": "Employer Stop-Loss Claims Recovery",
  "shortTitle": "Employer Stop-Loss Claims Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through employer stop-loss claims recovery",
  "industry": "Self-Funded Health Plan Recovery",
  "uiPort": 4593,
  "apiPort": 5593,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Employer Stop-Loss Claims Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "reimbursedAmount",
    "expectedKey": "eligibleAmount",
    "actualLabel": "Carrier Reimbursement",
    "expectedLabel": "Eligible Stop-Loss Recovery",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Employer Stop-Loss Claims Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("stop-loss-policy-library","ESL01","Stop-loss policy library","Execute stop-loss policy library using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed stop-loss policy library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Stop-loss policy library Reference","text","ESL01-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("covered-census-registry","ESL02","Covered census registry","Execute covered census registry using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed covered census registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Covered census registry Reference","text","ESL02-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("medical-claim-ingestion","ESL03","Medical claim ingestion","Execute medical claim ingestion using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed medical claim ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Medical claim ingestion Reference","text","ESL03-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("pharmacy-claim-ingestion","ESL04","Pharmacy claim ingestion","Execute pharmacy claim ingestion using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed pharmacy claim ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Pharmacy claim ingestion Reference","text","ESL04-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("specific-attachment-calculation","ESL05","Specific attachment calculation","Execute specific attachment calculation using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed specific attachment calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Specific attachment calculation Reference","text","ESL05-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("aggregate-attachment-calculation","ESL06","Aggregate attachment calculation","Execute aggregate attachment calculation using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed aggregate attachment calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Aggregate attachment calculation Reference","text","ESL06-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("aggregating-specific-deductible","ESL07","Aggregating-specific deductible","Execute aggregating-specific deductible using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed aggregating-specific deductible decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Aggregating-specific deductible Reference","text","ESL07-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("run-in-and-run-out-validation","ESL08","Run-in and run-out validation","Execute run-in and run-out validation using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed run-in and run-out validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Run-in and run-out validation Reference","text","ESL08-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("contract-basis-and-exclusion-analysis","ESL09","Contract basis and exclusion analysis","Execute contract basis and exclusion analysis using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed contract basis and exclusion analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Contract basis and exclusion analysis Reference","text","ESL09-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("paid-claim-evidence-package","ESL10","Paid-claim evidence package","Execute paid-claim evidence package using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed paid-claim evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Paid-claim evidence package Reference","text","ESL10-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("laser-and-amendment-control","ESL11","Laser and amendment control","Execute laser and amendment control using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed laser and amendment control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Laser and amendment control Reference","text","ESL11-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("carrier-submission-workflow","ESL12","Carrier submission workflow","Execute carrier submission workflow using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed carrier submission workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Carrier submission workflow Reference","text","ESL12-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("carrier-request-management","ESL13","Carrier request management","Execute carrier request management using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed carrier request management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Carrier request management Reference","text","ESL13-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("reimbursement-reconciliation","ESL14","Reimbursement reconciliation","Execute reimbursement reconciliation using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed reimbursement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","Reimbursement reconciliation Reference","text","ESL14-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]}),
feature("high-cost-claimant-forecasting","ESL15","High-cost claimant forecasting","Execute high-cost claimant forecasting using stop-loss policies, covered censuses, medical and pharmacy claims, attachment points, lasers, exclusions, paid-claim evidence, submissions, carrier responses, and reimbursements.","Produce a governed high-cost claimant forecasting decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Stop-Loss Policy","text","Employer / Stop-Loss Policy · Standard Case"],["caseReference","High-cost claimant forecasting Reference","text","ESL15-2026-001"],["reimbursedAmount","Carrier Reimbursement","currency",457000],["eligibleAmount","Eligible Stop-Loss Recovery","currency",539260],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Stop-loss policy library case","Covered census registry case","Medical claim ingestion case","Pharmacy claim ingestion case","Specific attachment calculation case"]})
]);
